import { MongooseModule } from "@nestjs/mongoose";
import {
  Video,
  VideoSchema,
  VideoDocName,
  User,
  UserSchema,
  UserDocName,
  Type,
  TypeSchema,
  TypeDocName,
  Topic,
  TopicSchema,
  TopicDocName,
  Gbook,
  GbookSchema,
  GbookDocName,
  Article,
  ArticleSchema,
  ArticleDocName,
  Admin,
  AdminSchema,
  AdminDocName,
  Actor,
  ActorSchema,
  ActorDocName,
  Group,
  GroupSchema,
  GroupDocName,
  Comment,
  CommentSchema,
  CommentDocName,
  Uact,
  UactSchema,
  UactDocName,
  Plog,
  PlogSchema,
  PlogDocName,
  Recharge,
  RechargeSchema,
  RechargeDocName,
  Distribute,
  DistributeSchema,
  DistributeDocName,
  Mag,
  MagSchema,
  MagDocName,
} from "../../schemas";

function useFactory(schema) {
  return schema;
}

export const RootModel = MongooseModule.forFeatureAsync([
  {
    name: User.name,
    useFactory: () => useFactory(UserSchema),
    collection: UserDocName,
  },
  {
    name: Video.name,
    useFactory: () => useFactory(VideoSchema),
    collection: VideoDocName,
  },
  {
    name: Article.name,
    useFactory: () => useFactory(ArticleSchema),
    collection: ArticleDocName,
  },
  {
    name: Gbook.name,
    useFactory: () => useFactory(GbookSchema),
    collection: GbookDocName,
  },
  {
    name: Admin.name,
    useFactory: () => useFactory(AdminSchema),
    collection: AdminDocName,
  },
  {
    name: Topic.name,
    useFactory: () => useFactory(TopicSchema),
    collection: TopicDocName,
  },
  {
    name: Type.name,
    useFactory: () => useFactory(TypeSchema),
    collection: TypeDocName,
  },
  {
    name: Actor.name,
    useFactory: () => useFactory(ActorSchema),
    collection: ActorDocName,
  },
  {
    name: Group.name,
    useFactory: () => useFactory(GroupSchema),
    collection: GroupDocName,
  },
  {
    name: Comment.name,
    useFactory: () => useFactory(CommentSchema),
    collection: CommentDocName,
  },
  {
    name: Distribute.name,
    useFactory: () => useFactory(DistributeSchema),
    collection: DistributeDocName,
  },
  {
    name: Recharge.name,
    useFactory: () => useFactory(RechargeSchema),
    collection: RechargeDocName,
  },
  {
    name: Uact.name,
    useFactory: () => useFactory(UactSchema),
    collection: UactDocName,
  },
  {
    name: Plog.name,
    useFactory: () => useFactory(PlogSchema),
    collection: PlogDocName,
  },
  {
    name: Mag.name,
    useFactory: () => useFactory(MagSchema),
    collection: MagDocName,
  },
]);
